

services:
  # =========================
  # Eureka Server
  # =========================
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  # =========================
  # MySQL Database
  # =========================
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservices_demo
      MYSQL_USER: root
      MYSQL_PASSWORD: Dada@1234
    ports:
      - "3306:3306"
    networks:
      - microservices-net

  # =========================
  # API Gateway
  # =========================
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - microservices-net

  # =========================
  # User Service
  # =========================
  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      - eureka-server
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dada@1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8081:8081"
    networks:
      - microservices-net

  # =========================
  # Product Service
  # =========================
  product-service:
    build: ./product-service
    container_name: product-service
    depends_on:
      - eureka-server
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dada@1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    networks:
      - microservices-net

  # =========================
  # Order Service
  # =========================
  order-service:
    build: ./order-service
    container_name: order-service
    depends_on:
      - eureka-server
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "java", "-jar", "app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/microservices_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Dada@1234
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    ports:
      - "8083:8083"
    networks:
      - microservices-net

# =========================
# Network
# =========================
networks:
  microservices-net:
    driver: bridge
